task :environment do
  Bundler.require(:default, ENV['RACK_ENV'])
  require "#{File.dirname(__FILE__)}/app"
end

namespace :assets do
  desc 'Precompile assets'
  task :precompile => :environment do
    App.assets.precompile
  end
end
